---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность оформления заказа с добавлением контакной информации пользователя
  - Пользователь должен иметь возможность удалять товары из корзины 
  - Пользователь должен иметь возможность возвращения к каталогу товаров из корзины с сохранением уже добавленных товаров в корзине
  - При оформлении заказа необходимо поле подтвержения заказа
  - Пользователь должен иметь возможность редактировать содержимое корзины (изменять количество позиций товара)
  - Сайт должен иметь форму регистраци и авторизации пользователя и проверять его аутентификацию
  - Форма авторизации должна содержать поля ввода - логина, пароля, номера телефона и/или электронной почты
  - Форма регистрации должна содержать поля ввода - логина, пароля, подтверждения пароля, номера телефона и/или электронной почты
  - В форме регистрации и авторизации в поле номера телефона должно быть 10 цифр и кнопка для ввода кода страны 
  - В форме авторизации и регистрации у пользователя должна быть возможность скрыть данные, которые он вводит в поле введения пароля
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения полей
  - Поле должно немедленно предупреждать пользователей, если они не заполняют поля формы авторизации или заполняют их неккоректно
  - Сайт должен быть адаптивным
  - Сайт должен быть кроссбраузерным
  - Сайт должен быть мультиязычным
  - Сайт должен работать по защищенному протоколу HTTPS
