---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге после добавления товаров в корзину
  - На странице товара и в каталоге должны выводиться - название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге 
  - На странице корзины пользователь может удалить товар из корзины и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина должна храниться в сессии браузера
   - Магазин будет SPA-приложение, которое не перезагружает страницу
  
implicit:
  - Пользователь должен виметь возможность сбросить выбранную категорию товаров
  - Пользователь должен иметь возможность оформления заказа с добавлением контакной информации пользователя
  - Пользователь должен иметь возможность удалять товары из корзины 
  - Пользователь должен иметь возможность возвращения к каталогу товаров из корзины с сохранением уже добавленных товаров в корзине
  - При оформлении заказа необходимо поле подтвержения заказа
  - Пользователь должен иметь возможность редактировать содержимое корзины (изменять количество позиций товара)
  - Пользователи должны иметь возможность использовать встроенную клавиатуру своего телефона для заполнения полей
  - Сайт должен быть адаптивным
  - Сайт должен быть мультиязычным
  - Сайт должен работать по защищенному протоколу HTTPS
